//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int OrderID { get; set; }
        public Nullable<int> SmallPizza { get; set; }
        public Nullable<int> MediumPizza { get; set; }
        public Nullable<int> BigPizza { get; set; }
        public Nullable<int> JumboPizza { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CustomerJMBG { get; set; }
        public string OrderStatus { get; set; }
    }
}
